const inventory = [ { id: 1,
    display_name: 'Off the shoulder top',
    price: 23.99,
    cost: 16,
    in_stock_count: 11 },
  { id: 2,
    display_name: 'High rise jean shorts',
    price: 44.99,
    cost: 31,
    in_stock_count: 24 },
  { id: 3,
    display_name: 'Fit and Flare dress',
    price: 105.99,
    cost: 95,
    in_stock_count: 5 },
  { id: 4,
    display_name: 'Sailor shorts',
    price: 29.99,
    cost: 20,
    in_stock_count: 7 },
  { id: 5,
    display_name: 'Leather cross-body clutch',
    price: 99.99,
    cost: 61,
    in_stock_count: 3 },
  { id: 6,
    display_name: 'White jeans-bootleg',
    price: 120,
    cost: 102,
    in_stock_count: 9 },
  { id: 7,
    display_name: 'Low rise jean cutoffs',
    price: 54.99,
    cost: 34,
    in_stock_count: 8 },
  { id: 8,
    display_name: 'Cotton shift dress',
    price: 19.99,
    cost: 16,
    in_stock_count: 14 },
  { id: 9,
    display_name: 'Artist earrings',
    price: 29.99,
    cost: 21,
    in_stock_count: 3 },
  { id: 10,
    display_name: 'Hair ties - pack of 7',
    price: 1.99,
    cost: 1,
    in_stock_count: 19 } ];

const item =   {
    "display_name": "High rise jean shorts new version",
    "price": 44.99,
    "cost": 31,
    "in_stock_count": 24
  };

module.exports = {
  inventory,
  item
};
